spring.application.name=legal-meterology
spring.datasource.url=jdbc:postgresql://localhost:5432/legal_metrology
spring.datasource.username=postgres
spring.datasource.password=Hari@postgres1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
$env:JWT_SECRET="+R4fUWnJdoBkX4hA84Ca4m0ug0JBjTsWmLdZMHPK2nk="