spring.application.name=legal-meterology
spring.datasource.url=jdbc:postgresql://localhost:5432/legal_metrology
spring.datasource.username=postgres
spring.datasource.password=AnuGrah#1234

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# JWT Security Configuration
jwt.secret=aGFja2F0aG9uLXNlY3JldC1rZXktbXVzdC1iZS1sb25nLWVub3VnaA==
jwt.expiration=86400000