spring.application.name=legal-meterology
spring.datasource.url=jdbc:postgresql://localhost:5432/legal_metrology
spring.datasource.username=postgres
spring.datasource.password=AnuGrah#1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
